### ISSUE TITLE
Missing dependency me.grison.raytraclj/my-kernel

### ISSUE THREAD

**Issue by enragedginger** [agrison/raytraclj#1]
Hello,

Thanks for putting this project together. I was going to try to run the final version myself and see what I could do to improve the performance since you mentioned in your blog post that the C++ performance was significantly better than performance for the Clojure version.

However, upon trying to run the project locally, it looks like this dependency is missing and I'm not sure where I should get it from: `me.grison.raytraclj/my-kernel`

**Comment by agrison** [comment]
You're totally right!

I've just pushed the **playing** branch, you can just pull the latest changes.

The `my-kernel` dependency is missing because it was a test I did locally to test Aparapi where you need to extends a Java abstract class, and didn't want the burden of doing it in Clojure so I just created another maven Java project with this class in it that I imported in my project.

I've removed the dependecy to it and aparapi, if you need it you'll need to add it again.

Thanks for trying, I'll be interested to see how you improve it. What I was thinking about was 

1. either to work directly with mutable `int-array` in Clojure instead of vectors, or even to externalize the `vec` class in Java. I guess a lot of objects gets created maybe this can be improved.
2. Improve the raytracing algorithm, clearly for a position `(x, y)` we already know that some `Hitable` won't be touched by the ray so it could be a good idea to avoir computing these rays for nothing.
3. Regarding the GPU I have near to zero knowledge about it so I didn't even know where to start.

Enjoy!

**Comment by agrison** [comment]
FWIW someone pointed me to the clojure2d project on Github (via Reddit) where it has already been implemented and it's waaayy faster than mine :)

https://github.com/Clojure2D/clojure2d-examples/tree/master/src/rt_in_weekend

Just be sure to change `map` to `pmap` at line 80 of file `ch12_random_scene.clj`, it's like 10 times faster and it renders on a canvas view in real time, really great!

**Comment by enragedginger** [comment]
That's cool. Good find on that. I was able to get your version running locally. I started swapping out everything in the `vec` namespace with `neanderthal`, but ran into issues once it came time to implement things like cross product and squared length. I didn't see an existing implementation of these in `neanderthal` and I struggled to find the parts necessary to build an efficient version of them myself. The fact that all of the function names are things like `dge`, `dv`, `axpy`, etc really bothers me. It makes the code unreadable.

I like the way `fastmath` is used in the example you linked. That's probably the best way to do this in Clojure.
